name: Deploy AutoTest Database1

on:
  push:
    paths:
      - 'setup.sql'
jobs:
  deploy-sql:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SQLCMD
        run: |
          sudo ACCEPT_EULA=Y apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev

      - name: Debug Print (no password)
        run: |
          echo "Host: $DB_HOST"
          echo "Port: $DB_PORT"
          echo "User: $DB_USER"

      - name: Run SQL Script
        run: |
          /opt/mssql-tools/bin/sqlcmd -S "$DB_HOST,$DB_PORT" -U "$DB_USER" -P "$DB_PASS" -i setup.sql

