name: Database Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SQL Server tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg apt-transport-https
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc
          /opt/mssql-tools/bin/sqlcmd -? || echo "sqlcmd installation failed"

      - name: Run SQL script
        env:
          SQL_SERVER1: ${{ secrets.SQL_SERVER1 }}
          SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        run: |
          /opt/mssql-tools/bin/sqlcmd -S $SQL_SERVER1 -U $SQL_USERNAME -P $SQL_PASSWORD  -i Database/create_timesheetdb.sql -o output.txt
          cat output.txt

      - name: Trigger SSIS Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-ssis
