name: Deploy TimesheetDB and SSIS Package with SQL Agent Job

on:
  push:
    branches:
      - main
    paths:
      - 'Database/**'
  workflow_dispatch:

env:
  SSIS_FOLDER_NAME: Timesheet
  SSIS_PROJECT_NAME: Integration Services Project1
  SSIS_PACKAGE_NAME: MigrateExcelData.dtsx
  SQL_AGENT_JOB_NAME: RunTimesheetMigration

jobs:
  deploy-and-schedule:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Deploy TimesheetDB using Windows authentication
    - name: Deploy TimesheetDB
      shell: cmd
      env:
        SQL_SERVER: ${{ secrets.SQL_SERVER }}
      run: |
        sqlcmd -S "%SQL_SERVER%" -E -i "Database\create_timesheetdb.sql"

    # Create SSISDB folder (Windows Auth only)
    - name: Create SSIS folder if not exists
      shell: cmd
      env:
        SQL_SERVER: ${{ secrets.SQL_SERVER }}
        SSIS_FOLDER_NAME: ${{ env.SSIS_FOLDER_NAME }}
      run: |
        echo USE SSISDB; > create_folder.sql
        echo IF NOT EXISTS (SELECT * FROM catalog.folders WHERE name = '%SSIS_FOLDER_NAME%') >> create_folder.sql
        echo BEGIN >> create_folder.sql
        echo   EXEC catalog.create_folder @folder_name = '%SSIS_FOLDER_NAME%'; >> create_folder.sql
        echo END >> create_folder.sql
        sqlcmd -S "%SQL_SERVER%" -E -i create_folder.sql

    # Deploy .ispac as VARBINARY using certutil + sqlcmd
    - name: Convert ISPAC to Hex and Deploy to SSISDB
      shell: cmd
      env:
        SQL_SERVER: ${{ secrets.SQL_SERVER }}
        SSIS_FOLDER_NAME: ${{ env.SSIS_FOLDER_NAME }}
        SSIS_PROJECT_NAME: ${{ env.SSIS_PROJECT_NAME }}
      run: |
        certutil -encodehex "Database\bin\Development\Integration Services Project1.ispac" ispac.hex 0x30
        echo SET NOCOUNT ON; > deploy_ssis.sql
        echo DECLARE @ispac_binary VARBINARY(MAX); >> deploy_ssis.sql
        echo SET @ispac_binary = 0x >> deploy_ssis.sql
        for /F "tokens=* usebackq" %%A in (`type ispac.hex`) do (
          echo %%A >> deploy_ssis.sql
        )
        echo ; >> deploy_ssis.sql
        echo DECLARE @operation_id BIGINT; >> deploy_ssis.sql
        echo EXEC SSISDB.catalog.deploy_project >> deploy_ssis.sql
        echo   @folder_name = N'%SSIS_FOLDER_NAME%', >> deploy_ssis.sql
        echo   @project_name = N'%SSIS_PROJECT_NAME%', >> deploy_ssis.sql
        echo   @project_stream = @ispac_binary, >> deploy_ssis.sql
        echo   @operation_id = @operation_id OUTPUT; >> deploy_ssis.sql
        echo SELECT @operation_id AS OperationID; >> deploy_ssis.sql
        sqlcmd -S "%SQL_SERVER%" -E -i deploy_ssis.sql

    # Create SQL Agent Job
    - name: Create SQL Agent Job
      shell: cmd
      env:
        SQL_SERVER: ${{ secrets.SQL_SERVER }}
        SSIS_FOLDER_NAME: ${{ env.SSIS_FOLDER_NAME }}
        SSIS_PROJECT_NAME: ${{ env.SSIS_PROJECT_NAME }}
        SSIS_PACKAGE_NAME: ${{ env.SSIS_PACKAGE_NAME }}
        SQL_AGENT_JOB_NAME: ${{ env.SQL_AGENT_JOB_NAME }}
        EXCEL_PATH: ${{ secrets.EXCEL_PATH }}
      run: |
        echo USE msdb; > create_job.sql
        echo IF EXISTS (SELECT 1 FROM sysjobs WHERE name = '%SQL_AGENT_JOB_NAME%') BEGIN >> create_job.sql
        echo   EXEC sp_delete_job @job_name = '%SQL_AGENT_JOB_NAME%'; >> create_job.sql
        echo END >> create_job.sql
        echo EXEC sp_add_job @job_name = N'%SQL_AGENT_JOB_NAME%', @enabled = 1, @description = N'Runs SSIS package daily'; >> create_job.sql
        echo EXEC sp_add_jobstep @job_name = N'%SQL_AGENT_JOB_NAME%', @step_name = N'Run SSIS', >> create_job.sql
        echo   @subsystem = N'SSIS', >> create_job.sql
        echo   @command = N'/ISSERVER "\"\SSISDB\%SSIS_FOLDER_NAME%\%SSIS_PROJECT_NAME%\%SSIS_PACKAGE_NAME%\"" /SERVER "%SQL_SERVER%" /Par "ExcelFilePath";"%EXCEL_PATH%"', >> create_job.sql
        echo   @database_name = N'master'; >> create_job.sql
        echo EXEC sp_add_jobschedule @job_name = N'%SQL_AGENT_JOB_NAME%', @name = N'DailyRun', @freq_type = 4, @freq_interval = 1, @active_start_time = 010000; >> create_job.sql
        echo EXEC sp_add_jobserver @job_name = N'%SQL_AGENT_JOB_NAME%'; >> create_job.sql
        sqlcmd -S "%SQL_SERVER%" -E -i create_job.sql
